---
# Install and configure all common packages across deployment

- name: packages | update all software packages
  yum: >
    name=*
    state=latest
  tags:
    - yum-update

- name: packages | install minimum package set
  yum: >
    name={{item}}
    state=latest
  with_items: "{{ role_packages_install_list }}"
  tags:
    - yum-packages

- name: packages | install yum-plugin-security for auto security updates
  yum: >
    name=yum-plugin-security
    state=latest
  tags:
    - yum-security-updates

- name: packages | configure daily security updates
  copy: >
    src=etc/cron.daily/yumupdate.sh
    dest=/etc/cron.daily/yumupdate.sh
    owner=root
    group=root
    mode=0755
  tags:
    - yum-security-updates
